
const LOWEST_NODE_VERSION = '12.0.0';
const STEAMED_CLI_HOME_PATH = '.steamed';
const STEAMED_CLI_LOG_LEVEL = 'info';

module.exports = {
    LOWEST_NODE_VERSION,
    STEAMED_CLI_HOME_PATH,
    STEAMED_CLI_LOG_LEVEL
}